Update generatewg_

diff --git a/generatewg_ b/generatewg_
--- a/generatewg_
+++ b/generatewg_
@@ -137,6 +137,142 @@ if [ -f ${WGSCONFPATH} ]
 
 #DETERMINE WIREGAURD INTERFACE IP AND NETWORK FROM SENTINAL FILES, CONFIGURATION FILE, OR CREATE NEW FROM DEFAULT LAN AS TEMPLATE (X.X.Y.1/24)
 #VERIFY SENTINAL AND CONFIGURATION FILE CONTINUITY AGAINST SCRIPT SETTING, IF CHANGED MODIFIES ALL "CLIENT"/PEER CONFIGURATION FILES TO MATCH
+cidrtomask () {
+	if [ -z $1 ]
+		then
+			printf "CIDR bit length not provided to cidrtomask function!\n" 1>&2
+			exit 1
+		fi
+	local i mask=""
+	local full_octets=$(($1/8))
+	local partial_octet=$(($1%8))
+	for ((i=0;i<4;i+=1))
+		do
+			if [ $i -lt $full_octets ]
+				then
+					mask+=255
+			elif [ $i -eq $full_octets ]
+				then
+					mask+=$((256 - 2**(8-$partial_octet)))
+				else
+					mask+=0
+				fi  
+			test $i -lt 3 && mask+=.
+		done
+	printf "$mask"
+}
+networkmin () {
+	if [ -z $1 ] || ! grep -q '/' <<< "$1"
+		then
+			printf "CIDR network not provided to networkmin function!\n" 1>&2
+			exit 1
+		fi
+	local i1 i2 i3 i4 m1 m2 m3 m4
+	IFS=. read -r i1 i2 i3 i4 <<< "$(cut -d'/' -f1 <<< $1})"
+	IFS=. read -r m1 m2 m3 m4 <<< "$(cidrtomask `cut -d'/' -f2 <<< $1`)"
+	printf "%d.%d.%d.%d" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$(( ( i4 & m4 ) + 1 ))"
+}
+networkmax () {
+	if [ -z $1 ] || ! grep -q '/' <<< "$1"
+		then
+			printf "CIDR network not provided to networkmax function!\n" 1>&2
+			exit 1
+		fi
+	local i1 i2 i3 i4 m1 m2 m3 m4
+	IFS=. read -r i1 i2 i3 i4 <<< "$(cut -d'/' -f1 <<< $1)"
+	IFS=. read -r m1 m2 m3 m4 <<< "$(cidrtomask `cut -d'/' -f2 <<< $1`)"
+	printf "%d.%d.%d.%d" "$(( ( 255 ^ m1 ) | i1 ))" "$(( ( 255 ^ m2 ) | i2 ))" "$(( ( 255 ^ m3 ) | i3 ))" "$(( ( ( 255 ^ m4 ) | i4 ) - 1 ))"
+}
+clientconfignetwork () {
+	#WARNING!!!! This function has the potential to "guess" prior existing networks based on "client"/peer configurations wrong!
+	local a1 a2 a3 a4 a5 check lowest highest laddress haddress address=''
+	if [ -d $WGSDIR ]
+		then
+			for x in $(find $WGSDIR -maxdepth 1 -mindepth 1 -type d)
+				do
+					WGC=$(printf "$x"|rev|cut -d'/' -f 1|rev)
+					if [ -f $x/$WGCaddress ]
+						then
+							a1=$(<$x/$WGCaddress)
+					elif [ -f $x/$WGC.conf ]
+						then
+							a1=$(grep 'Address = ' $x/$WGC.conf|rev|cut -d' ' -f1|rev)
+							printf "$a1" > $x/$WGCaddress
+						fi
+					if [ ! -z $a1 ]
+						then
+							a5=$(cut -d'/' -f2 <<< "$a1")
+							IFS=. read -r a1 a2 a3 a4 <<< $(cut -d'/' -f1 <<< "$a1")
+							check=$(( a1 + a2 + a3 + a4 ))
+							if [ -z $lowest ]
+								then
+									lowest=$check
+									highest=$check
+								else
+									if [ $check -lt $lowest ]
+										then
+											lowest=$check
+											laddress="$a1.$a2.$a3.a4/$a5"
+										fi
+									if [ $check -gt $highest ]
+										then
+											highest=$check
+											haddress="$a1.$a2.$a3.a4/$a5"
+										fi
+								fi
+							a1=''
+						fi
+				done
+			if [ -z $lowest ]
+				then
+					printf 'clientconfignetwork function could not determine any client configurations!\n' 1>&2
+					return
+			elif [ $lowest = $highest ]
+				then
+					printf 'clientconfignetwork function could not determine network range from client configurations!\n' 1>&2
+					return
+				else
+					lowest=$(networkmin "$laddress")
+					highest=$(networkmin "$haddress")
+					if [ $lowest = $highest ]
+						then
+							highest=$(ip route get "$lowest"|grep 'via')
+							if [ ! -z $highest ]
+								then
+									highest=$(networkmax "$haddress")
+									IFS=. read -r a1 a2 a3 a4 <<< "$lowest"
+									a5=$(( a4 + 1 ))
+									IFS=. read -r a1 a2 a3 a4 <<< $(cut -d'/' -f1 <<< "$laddress")
+									if [ $a5 = $a4]
+										then
+											address=$lowest
+										else
+											IFS=. read -r a1 a2 a3 a4 <<< "$highest"
+											a5=$(( a4 - 1 ))
+											IFS=. read -r a1 a2 a3 a4 <<< $(cut -d'/' -f1 <<< "$haddress")
+											if [ $a5 = $a4]
+												then
+													address=$highest
+												else
+													printf 'clientconfignetwork function could not determine Wiregaurd network!\n' 1>&2
+													return
+												fi
+										fi
+								else
+									printf 'clientconfignetwork function determined a network that is in use!\n' 1>&2
+									return
+								fi
+						else
+							printf 'clientconfignetwork function could not determine a contigous network!\n' 1>&2
+							return
+						fi
+				fi
+		else
+			printf 'No Wiregaurd server configuration directory for clientconfignetwork function!\n' 1>&2
+			return
+		fi
+	printf "$address,$laddress,$haddress"
+}
 if [ -z $WG_IFACE_NTWRK ]
 	then
 		if [ -f ${WGSDIR}address ]
@@ -145,10 +281,31 @@ if [ -z $WG_IFACE_NTWRK ]
 		else
 			if [ -z $WGSCONF ]
 				then
+					WG_IFACE_NTWRK=$(clientconfignetwork)
+					if [ -z $WG_IFACE_NTWRK ]
+						then
+							WG_ADDRESS_RANGE_BEG=$(networkmin "$WG_IFACE_NTWRK")
+							if 
+							WG_ADDRESS_RANGE_END=$(networkmax "$WG_IFACE_NTWRK")
+						else
+							WG_ADDRESS_RANGE_BEG=$(cut -d',' -f2 <<< "$WG_IFACE_NTWRK")
+							WG_ADDRESS_RANGE_END=$(cut -d',' -f3 <<< "$WG_IFACE_NTWRK")
+							WG_IFACE_NTWRK=$(cut -d',' -f1 <<< "$WG_IFACE_NTWRK")
+						fi
+
+
+#clientconfignetwork check server config file?
+#bitwise push CIDR mask to a mask with matching end bit
+#
+
+
+
+							WG_IFACE_NTWRK=$(???)
+							WG_ADDRESS_RANGE_BEG=$(networkmin "$WG_IFACE_NTWRK")
+							WG_ADDRESS_RANGE_END=$(networkmax "$WG_IFACE_NTWRK")
 					printf "Script WG_IFACE_NTWRK variable not set!\n"
 					WG_IFACE_NTWRK=$(ip route show default|rev|cut -d' ' -f1|rev)
-					WG_IFACE_NTWRK=$(ip address show "$WG_IFACE_NTWRK"|grep 'inet '|cut -d' ' -f6|cut -d'/' -f1)
-					WG_ADDRESS_RANGE_BEG=$(cut -d'.' -f3 <<< $WG_IFACE_NTWRK)
+					WG_IFACE_NTWRK=$(ip address show "$WG_IFACE_NTWRK"|grep 'inet '|cut -d' ' -f6)
 					WG_IFACE_NTWRK="${WG_IFACE_NTWRK//.$WG_ADDRESS_RANGE_BEG./..}"
 					WG_ADDRESS_RANGE_BEG=$(cut -d'.' -f4 <<< $WG_IFACE_NTWRK)
 					WG_IFACE_NTWRK=${WG_IFACE_NTWRK%$WG_ADDRESS_RANGE_BEG}
@@ -178,8 +335,14 @@ if [ -z $WG_IFACE_NTWRK ]
 					printf "WG_IFACE_NTWRK set to $WG_IFACE_NTWRK!\n\
 WG_ADDRESS_RANGE_BEG set to $WG_ADDRESS_RANGE_BEG!\n\
 WG_ADDRESS_RANGE_END set to $WG_ADDRESS_RANGE_END!\n"
+
+
+
+
+
+
 				else
-					WG_IFACE_NTWRK=$(grep 'Address = ' <<< "${WGSCONF}"|rev|cut -d' ' -f1|rev)
+					WG_IFACE_NTWRK=$(grep 'Address = ' <<< "$WGSCONF"|rev|cut -d' ' -f1|rev)
 				fi
 			printf "${WG_IFACE_NTWRK}">"${WGSDIR}address"
 		fi
